apiVersion: v2
name: fastapi-app
description: A Helm chart for Kubernetes
version: 0.1.0
appVersion: "v1.0.1"
keywords:
  - fastapi
  - kubernetes
maintainers:
  - name: Naveen
    email: naveen.yerravarapu2000@gmail.com
